version: '2'

services:
  web:
    image: giggio/mongodbdotnetcore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - "db"
    environment:
      - Mongo:ConnectionString=mongodb://db:27017
  db:
    image: mongo
    ports:
      - "27017"